<a href="https://colab.research.google.com/github/devadathprabhu/DSC611/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier

import pandas as pd
import numpy as np

In [3]:
iris = datasets.load_iris()
print(iris.DESCR)
print(iris.feature_names)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
X = iris["data"]
Y = iris["target"]

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,train_size=0.8)

log_clf = LogisticRegression(max_iter=1000)
log_clf.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

In [9]:
log_pred = log_clf.predict(X_test)
log_pred

array([2, 0, 2, 2, 2, 2, 1, 2, 0, 1, 0, 2, 2, 2, 2, 0, 1, 1, 2, 2, 0, 0,
       2, 0, 0, 1, 1, 1, 0, 0])

In [10]:
Y_test

array([2, 0, 2, 2, 2, 2, 1, 2, 0, 1, 0, 2, 2, 2, 2, 0, 1, 1, 2, 2, 0, 0,
       2, 0, 0, 1, 1, 1, 0, 0])

In [11]:
sgd_clf = SGDClassifier(loss='log')
sgd_clf.fit(X_train, Y_train)

SGDClassifier(loss='log')

In [14]:
sgd_predict = sgd_clf.predict(X_test)
sgd_predict

array([1, 0, 2, 1, 1, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0])

In [15]:
probe = sgd_clf.predict_proba(X_test)
probe

array([[6.17080902e-061, 5.00000000e-001, 5.00000000e-001],
       [1.00000000e+000, 4.32963658e-024, 4.58116619e-294],
       [2.06973185e-044, 5.00000000e-001, 5.00000000e-001],
       [2.59194822e-041, 5.00006712e-001, 4.99993288e-001],
       [2.27177306e-042, 1.00000000e+000, 2.38341774e-012],
       [1.00644533e-045, 5.00000000e-001, 5.00000000e-001],
       [9.58263911e-028, 1.00000000e+000, 8.67401283e-085],
       [2.26302399e-052, 5.00000000e-001, 5.00000000e-001],
       [1.00000000e+000, 9.55075251e-053, 0.00000000e+000],
       [2.41688706e-030, 1.00000000e+000, 5.27393031e-069],
       [9.91766448e-001, 8.23355207e-003, 9.46388238e-297],
       [5.77020614e-046, 5.00000000e-001, 5.00000000e-001],
       [6.44065098e-055, 5.00000000e-001, 5.00000000e-001],
       [1.30197490e-049, 5.00000000e-001, 5.00000000e-001],
       [3.91682445e-050, 1.00000000e+000, 4.99419884e-021],
       [1.00000000e+000, 1.90919574e-018, 0.00000000e+000],
       [2.49569564e-030, 1.00000000e+000

In [16]:
from sklearn.metrics import confusion_matrix

conf_log = confusion_matrix(Y_test, log_pred)
conf_sgd = confusion_matrix(Y_test, sgd_predict)

print("Confusion matrix for Logistic Model")
print(conf_log)

print("Confusion matrix for LogSGDistic Model")
print(conf_sgd)

Confusion matrix for Logistic Model
[[10  0  0]
 [ 0  7  0]
 [ 0  0 13]]
Confusion matrix for LogSGDistic Model
[[10  0  0]
 [ 0  7  0]
 [ 0 10  3]]


In [17]:
from sklearn.metrics import accuracy_score

accuracy_score(Y_test, log_pred)

1.0

In [18]:
accuracy_score(Y_test, sgd_predict)

0.6666666666666666