<a href="https://colab.research.google.com/github/devadathprabhu/DSC611/blob/main/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


1 Given 2 numpy arrays of same dimension, compute the element-wise sum of the arrays

In [8]:
import numpy as np

list1 = [1,2,3]
array1 = np.array(list1)
list2 = [10, 11, 12]
array2 = np.array(list2)
array1+array2

array([11, 13, 15])

2 Compute the product of a scalar multiplied by a numpy array.

In [ ]:
k = 10
k*array1

3 Create an identity matrix of dimension n

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

4 Transform a 3-D array to a 1-D array

In [16]:
array3D = np.array([[(1, 2, 3), (4, 5, 6)],[(1, 2, 3), (4, 5, 6)]])
array3D
array3D.shape
array3D.reshape(-1)

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

5 Convert the data type of all float elements to integer.

In [22]:
floatarray = np.array([1.1, 2.5, 3, 4.0])
floatarray
intarray = floatarray.astype(int)
intarray

array([1, 2, 3, 4])

6 Print the reverse of a vector


In [25]:
intarray
reversedarray = intarray[::-1]
reversedarray

array([4, 3, 2, 1])

7 Initialize a vector
i. with values ranging from 20 to 50
ii. with random values and find the maximum and minimum values. Also
compute the mean.
iii. with random values between 20 and 50.

8 Create a numpy vector
i. with 5 elements between 20 and 100 (evenly spaced) 
ii. with elements between 20 and 100 (evenly spaced with step of 5)

9 Perform the following stacking operations on a numpy array:
i. Horizontal stacking
ii. Vertical stacking

In [32]:
arrayHStack = np.hstack((intarray, reversedarray)) # should have same number of rows
arrayHStack

array([1, 2, 3, 4, 4, 3, 2, 1])

In [33]:
arrayVStack = np.vstack((intarray, reversedarray)) # should have same number of columns
arrayVStack

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

10 Compute the product of two 2D numpy arrays.

In [35]:
arrayVStack * arrayVStack

array([[ 1,  4,  9, 16],
       [16,  9,  4,  1]])

11 Determine the transpose of a numpy array.

In [38]:
arrayVStack.transpose()

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

12 Display
i. all odd elements from a numpy array.
ii. indices of common elements in 2 arrays..

In [40]:
arrayVStack[arrayVStack%2==1]

array([1, 3, 3, 1])

In [44]:
array1 = np.array([1,2,3,4])
array2 = np.array([2,4,6,8])
np.nonzero(np.in1d(array1, array2))[0]

array([1, 3])